module.exports = {
    account_model_update: 1,
    lock_edit: 2,
    key_created: 3,
    key_remove: 4,
    key_edit: 5,
    debug: 6,
    connected: 7,
    disconnected: 8,
    account_created: 9,
    account_login: 10,
    lock_created: 11,
    lock_registered: 12,
    invalid_action: 13,
    new_event: 14,
    lock_lock_command: 15,
    lock_unlock_command: 16,
    lock_lock_command_fail: 17,
    lock_lock_command_success: 18,
    lock_unlock_command_fail: 19,
    lock_unlock_command_success: 20,
    invalid_password: 21
};